import './globals.css';
import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import localFont from 'next/font/local';

const lexend = localFont({
  src: [
    {
      path: '../public/fonts/lexend-latin-400-normal.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/lexend-latin-500-normal.woff',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/lexend-latin-700-normal.woff',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/lexend-latin-900-normal.woff',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-lexend', // optional: creates a CSS variable
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <body className={`${lexend.className} font-sans`}>{children}</body>
      </AppRouterCacheProvider>
    </html>
  );
}
